services:

  nats1:
    image: docker.io/nats:2.9.20
    container_name : "nats1"
    volumes:
      - ./data1:/data
    command:
      - "--name=nats1"
      - "--port=30041"
      - "--js"
      - "--sd=/data"
    network_mode: host
    restart: always
  
  natsriot1:
    container_name: natsriot1
    image: ashupednekar535/tools:natsriot
    environment:
      - SOURCE_SERVER_ADDR=nats://localhost:30041
      - DESTINATION_SERVER_ADDR=nats://localhost:30042
    network_mode: host
    restart: always
